import { z } from "zod";
import { RoleSchema } from "@financeos/shared";

export const AbstentionTriggerSchema = z.enum([
  "insufficient_evidence",
  "conflicting_evidence",
  "out_of_scope",
  "insufficient_permissions",
  "data_too_sensitive",
  "policy_violation",
  "confidence_too_low",
  "hallucination_risk",
  "materiality_threshold",
  "pending_approval",
  "audit_hold",
  "missing_required_evidence",
]);
export type AbstentionTrigger = z.infer<typeof AbstentionTriggerSchema>;

export const AbstentionPolicySchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  description: z.string(),
  trigger: AbstentionTriggerSchema,
  condition: z.string(),
  appliesToRoles: z.array(RoleSchema),
  appliesToDataDomains: z.array(z.string()),
  responseTemplate: z.string(),
  escalateTo: RoleSchema.optional(),
  requiresApproval: z.boolean().default(false),
  logOnTrigger: z.boolean().default(true),
  isActive: z.boolean().default(true),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type AbstentionPolicy = z.infer<typeof AbstentionPolicySchema>;

export const DEFAULT_ABSTENTION_POLICIES: AbstentionPolicy[] = [
  {
    id: "abs000001-0000-0000-0000-000000000001",
    name: "Insufficient Evidence — RAG",
    description: "Abstain when fewer than 2 evidence chunks are retrieved with confidence ≥ 0.6.",
    trigger: "insufficient_evidence",
    condition: "retrieval_count < 2 OR max_chunk_score < 0.6",
    appliesToRoles: ["viewer", "analyst", "operator", "finance_manager", "controller", "cfo", "auditor", "admin"],
    appliesToDataDomains: ["documents", "policies", "contracts"],
    responseTemplate: "I don't have enough reliable source material to answer confidently. Please provide relevant policy documents or check the document library.",
    requiresApproval: false,
    logOnTrigger: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "abs000001-0000-0000-0000-000000000002",
    name: "Materiality Threshold — Metric Override",
    description: "Abstain and escalate when requested metric change exceeds materiality threshold of $10K or 5%.",
    trigger: "materiality_threshold",
    condition: "abs(requested_change_usd) > 10000 OR abs(requested_change_pct) > 0.05",
    appliesToRoles: ["analyst", "operator", "finance_manager"],
    appliesToDataDomains: ["metrics"],
    responseTemplate: "This change exceeds the materiality threshold ($10K or 5%). I've drafted the adjustment for controller review — no value has been changed. Please route the approval request.",
    escalateTo: "controller",
    requiresApproval: true,
    logOnTrigger: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "abs000001-0000-0000-0000-000000000003",
    name: "Confidential Column Access Blocked",
    description: "Abstain and block when a query touches a column classified RESTRICTED or TOP_SECRET for the requestor's role.",
    trigger: "data_too_sensitive",
    condition: "column_sensitivity IN ('restricted', 'top_secret') AND role NOT IN requiredRoles",
    appliesToRoles: ["viewer", "analyst", "operator", "finance_manager"],
    appliesToDataDomains: ["users", "compensation", "strategic_plans"],
    responseTemplate: "I'm unable to surface that information — it's classified above your current access level. Contact your system administrator if you believe access is required.",
    requiresApproval: false,
    logOnTrigger: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "abs000001-0000-0000-0000-000000000004",
    name: "Conflicting Evidence — Policy Compliance",
    description: "Abstain when retrieved policy documents produce conflicting guidance on the same question.",
    trigger: "conflicting_evidence",
    condition: "evidence_conflict_score > 0.4",
    appliesToRoles: ["viewer", "analyst", "operator", "finance_manager", "controller", "cfo", "auditor", "admin"],
    appliesToDataDomains: ["policies", "contracts"],
    responseTemplate: "The available source documents contain conflicting guidance on this topic. I'm surfacing both perspectives below but cannot provide a definitive answer. Please consult your compliance team for resolution.",
    requiresApproval: false,
    logOnTrigger: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "abs000001-0000-0000-0000-000000000005",
    name: "Pending Approval — Draft Actions",
    description: "Abstain from executing any action that has a corresponding pending approval request.",
    trigger: "pending_approval",
    condition: "action_type IN approved_actions AND approval_status = 'pending'",
    appliesToRoles: ["analyst", "operator", "finance_manager", "controller"],
    appliesToDataDomains: ["metrics", "workflows", "close_tasks"],
    responseTemplate: "This action is awaiting approval. I've drafted the recommendation but cannot execute until the approval workflow completes. Track progress in the Approvals queue.",
    requiresApproval: true,
    logOnTrigger: true,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "abs000001-0000-0000-0000-000000000006",
    name: "Out-of-Scope — Non-Finance Query",
    description: "Abstain when query intent is classified as outside the finance operations domain.",
    trigger: "out_of_scope",
    condition: "query_domain_score < 0.3",
    appliesToRoles: ["viewer", "analyst", "operator", "finance_manager", "controller", "cfo", "auditor", "admin"],
    appliesToDataDomains: ["*"],
    responseTemplate: "This question is outside the scope of FinanceOS. I can help with financial analysis, variance commentary, policy compliance, reconciliation, and close management.",
    requiresApproval: false,
    logOnTrigger: false,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
];
