import { z } from "zod";
import { RoleSchema } from "@financeos/shared";

export const EvidenceTypeSchema = z.enum([
  "document",
  "metric",
  "rag_chunk",
  "audit_event",
  "approval",
  "external_report",
  "screenshot",
  "gl_export",
]);
export type EvidenceType = z.infer<typeof EvidenceTypeSchema>;

export const EvidenceRequirementSchema = z.object({
  id: z.string().uuid(),
  name: z.string(),
  description: z.string(),
  appliesToAction: z.string(),
  appliesToRoles: z.array(RoleSchema),
  minimumEvidenceCount: z.number().int().min(1),
  requiredEvidenceTypes: z.array(EvidenceTypeSchema),
  minimumConfidenceScore: z.number().min(0).max(1).optional(),
  requiresTimestampedSource: z.boolean().default(false),
  requiresPeerReview: z.boolean().default(false),
  requiresDocumentReference: z.boolean().default(false),
  retentionPeriodDays: z.number().int(),
  isActive: z.boolean().default(true),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type EvidenceRequirement = z.infer<typeof EvidenceRequirementSchema>;

export const EVIDENCE_REQUIREMENTS: EvidenceRequirement[] = [
  {
    id: "er000001-0000-0000-0000-000000000001",
    name: "Variance Commentary",
    description: "Any AI-generated variance explanation must cite at least 2 data sources with confidence ≥ 0.7.",
    appliesToAction: "variance.explain",
    appliesToRoles: ["analyst", "finance_manager", "controller", "cfo"],
    minimumEvidenceCount: 2,
    requiredEvidenceTypes: ["metric", "rag_chunk"],
    minimumConfidenceScore: 0.7,
    requiresTimestampedSource: true,
    requiresPeerReview: false,
    requiresDocumentReference: false,
    retentionPeriodDays: 2555,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "er000001-0000-0000-0000-000000000002",
    name: "Metric Override Justification",
    description: "Metric value overrides require a GL export or CFO memo plus an approval event.",
    appliesToAction: "metric.override",
    appliesToRoles: ["controller", "cfo", "admin"],
    minimumEvidenceCount: 2,
    requiredEvidenceTypes: ["gl_export", "approval"],
    minimumConfidenceScore: undefined,
    requiresTimestampedSource: true,
    requiresPeerReview: true,
    requiresDocumentReference: true,
    retentionPeriodDays: 2555,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "er000001-0000-0000-0000-000000000003",
    name: "Close Sign-Off Evidence",
    description: "Period-end close sign-off requires the close checklist, reconciliation confirmation, and an approval record.",
    appliesToAction: "close.sign_off",
    appliesToRoles: ["controller", "cfo"],
    minimumEvidenceCount: 3,
    requiredEvidenceTypes: ["document", "approval", "audit_event"],
    requiresTimestampedSource: true,
    requiresPeerReview: false,
    requiresDocumentReference: true,
    retentionPeriodDays: 2555,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "er000001-0000-0000-0000-000000000004",
    name: "Policy Compliance Answer",
    description: "Compliance answers must cite at least 1 policy document chunk with score ≥ 0.75.",
    appliesToAction: "policy.check",
    appliesToRoles: ["analyst", "finance_manager", "controller", "cfo", "auditor"],
    minimumEvidenceCount: 1,
    requiredEvidenceTypes: ["rag_chunk", "document"],
    minimumConfidenceScore: 0.75,
    requiresTimestampedSource: false,
    requiresPeerReview: false,
    requiresDocumentReference: true,
    retentionPeriodDays: 1825,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
  {
    id: "er000001-0000-0000-0000-000000000005",
    name: "Reconciliation Clearing Entry",
    description: "Any suggested clearing journal entry requires a GL export and reconciliation report as evidence.",
    appliesToAction: "reconciliation.draft_je",
    appliesToRoles: ["analyst", "finance_manager", "controller"],
    minimumEvidenceCount: 2,
    requiredEvidenceTypes: ["gl_export", "document"],
    requiresTimestampedSource: true,
    requiresPeerReview: true,
    requiresDocumentReference: true,
    retentionPeriodDays: 2555,
    isActive: true,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
  },
];
