import { z } from "zod";

export const ModelCapabilitySchema = z.enum([
  "text_generation",
  "embeddings",
  "classification",
  "function_calling",
  "rag",
  "reasoning",
  "vision",
  "code",
]);
export type ModelCapability = z.infer<typeof ModelCapabilitySchema>;

export const ModelProviderSchema = z.enum([
  "openai",
  "anthropic",
  "google",
  "azure_openai",
  "cohere",
  "mistral",
  "internal",
]);

export const BiasAssessmentSchema = z.enum(["not_assessed", "low", "medium", "high"]);

export const ModelCardSchema = z.object({
  id: z.string().uuid(),
  modelId: z.string(),
  displayName: z.string(),
  provider: ModelProviderSchema,
  version: z.string(),
  capabilities: z.array(ModelCapabilitySchema),
  contextWindowTokens: z.number().int(),
  maxOutputTokens: z.number().int(),
  allowedUseCases: z.array(z.string()),
  restrictedDataDomains: z.array(z.string()),
  approvedForProduction: z.boolean().default(false),
  approvedBy: z.string().optional(),
  approvedAt: z.string().datetime().optional(),
  biasAssessment: BiasAssessmentSchema,
  complianceFrameworks: z.array(z.string()),
  deployedEnvironments: z.array(z.enum(["development", "staging", "production"])),
  averageLatencyMs: z.number().optional(),
  costPer1kTokensUsd: z.number().optional(),
  deprecatedAt: z.string().datetime().optional(),
  notes: z.string().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type ModelCard = z.infer<typeof ModelCardSchema>;

export const MODEL_REGISTRY: ModelCard[] = [
  {
    id: "mr000001-0000-0000-0000-000000000001",
    modelId: "gpt-4o-2024-08-06",
    displayName: "GPT-4o (Aug 2024)",
    provider: "openai",
    version: "2024-08-06",
    capabilities: ["text_generation", "function_calling", "rag", "reasoning", "vision", "code"],
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    allowedUseCases: [
      "variance_commentary",
      "policy_compliance",
      "close_management",
      "ar_collections",
      "ap_invoice_research",
      "reconciliation",
    ],
    restrictedDataDomains: ["compensation", "strategic_plans"],
    approvedForProduction: true,
    approvedBy: "James Okafor (CFO)",
    approvedAt: "2025-06-01T00:00:00Z",
    biasAssessment: "low",
    complianceFrameworks: ["SOX", "GAAP", "IFRS"],
    deployedEnvironments: ["development", "staging", "production"],
    averageLatencyMs: 1400,
    costPer1kTokensUsd: 0.0025,
    notes: "Primary model for all finance workflow agents and Ask AI chat.",
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "mr000001-0000-0000-0000-000000000002",
    modelId: "text-embedding-3-large",
    displayName: "Text Embedding 3 Large",
    provider: "openai",
    version: "1",
    capabilities: ["embeddings"],
    contextWindowTokens: 8191,
    maxOutputTokens: 0,
    allowedUseCases: ["rag_indexing", "semantic_search", "document_similarity"],
    restrictedDataDomains: [],
    approvedForProduction: true,
    approvedBy: "James Okafor (CFO)",
    approvedAt: "2025-06-01T00:00:00Z",
    biasAssessment: "low",
    complianceFrameworks: ["SOX"],
    deployedEnvironments: ["development", "staging", "production"],
    averageLatencyMs: 120,
    costPer1kTokensUsd: 0.00013,
    notes: "Used for all RAG document embeddings and hybrid retrieval.",
    createdAt: "2025-06-01T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "mr000001-0000-0000-0000-000000000003",
    modelId: "claude-3-5-sonnet-20241022",
    displayName: "Claude 3.5 Sonnet",
    provider: "anthropic",
    version: "20241022",
    capabilities: ["text_generation", "rag", "reasoning", "code"],
    contextWindowTokens: 200000,
    maxOutputTokens: 8192,
    allowedUseCases: ["policy_compliance", "document_analysis", "audit_review"],
    restrictedDataDomains: ["compensation"],
    approvedForProduction: false,
    biasAssessment: "low",
    complianceFrameworks: ["SOX", "GDPR"],
    deployedEnvironments: ["development", "staging"],
    averageLatencyMs: 1800,
    costPer1kTokensUsd: 0.003,
    notes: "Approved for staging use in policy compliance. Production approval pending security review.",
    createdAt: "2025-07-01T00:00:00Z",
    updatedAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "mr000001-0000-0000-0000-000000000004",
    modelId: "gpt-4o-mini-2024-07-18",
    displayName: "GPT-4o Mini",
    provider: "openai",
    version: "2024-07-18",
    capabilities: ["text_generation", "classification", "function_calling"],
    contextWindowTokens: 128000,
    maxOutputTokens: 16384,
    allowedUseCases: ["query_classification", "routing", "simple_qa"],
    restrictedDataDomains: ["compensation", "strategic_plans", "forecasts"],
    approvedForProduction: true,
    approvedBy: "J. Davies (Controller)",
    approvedAt: "2025-08-01T00:00:00Z",
    biasAssessment: "low",
    complianceFrameworks: ["SOX"],
    deployedEnvironments: ["development", "staging", "production"],
    averageLatencyMs: 380,
    costPer1kTokensUsd: 0.00015,
    notes: "Used only for orchestration routing and query classification. Not used for financial analysis answers.",
    createdAt: "2025-08-01T00:00:00Z",
    updatedAt: "2025-08-01T00:00:00Z",
  },
];
